### ISSUE TITLE
Web - Fix Remaining Follower/Following Related Issues

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#357]
- [x] Fix the styling of the follower and following modals
- [x] Add the modals to the profile page.

**Comment by ozturkMirac** [comment]
We started making corrections to the followers and following models with @EgemenKaplan . 
He dedicated valuable time to me and contributed to clarifying things in my mind.

Done:
- The follower and following models were hard-coded due to my lack of experience. 
- I made efforts to correct them and implement more practical solutions. 
- I presented users in a list format.
