### ISSUE TITLE
Revise Class Diagrams

### ISSUE THREAD

**Issue by alabeybahri** [bounswe/bounswe2023group8#57]
Revision of class diagrams.

**Comment by EgemenKaplan** [comment]
-  Class diagrams had a decent overhaul. There were some wrong diagrams in our class diagram collection, which were confused as database tables rather than class diagrams. These were removed and replaced as Lists within their respective classes. 

- Missing class diagrams were added.

- Most diagrams were missing methods and properties. This was fixed.

TO DO
- Relation arrows between class diagrams still need to be fixed.

There will possibly more additions to class diagrams as sequence diagrams evolve.  Here is a glimpse of the current state of class diagrams:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/22966868/230744279-a5bfcc83-0eed-4876-ae75-0299ded2fa57.png">

**Comment by alabeybahri** [comment]
-  Specified the types of relationships between classes, and fixed the arrows accordingly. We added a legend for the relationship types, represented by the lines. 

-  Added multiplicity values for each relationship. 

- Added some missing relationship arrows. 

Here is the current state of class diagrams:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/73395803/230783301-f7f52880-df6f-4012-b7e5-3e90777d27d3.png">
