### ISSUE TITLE
Add Mockups to Milestone 1 Report Page

### ISSUE THREAD

**Issue by FurkanOzcelik** [bounswe/bounswe2023group8#78]
Milestone 1 Report Page has already been created. There is a "Mockups" section. 

- [x] Group Mockups semantically and name them.
- [ ] Take screenshots of our Mockups and add them to corresponding section.

**Comment by bakikucukcakiroglu** [comment]
I grouped Mobile Mockups semantically and named them.

**Comment by bakikucukcakiroglu** [comment]
I grouped Web Mockups semantically and named them.

**Comment by MericKeskin** [comment]
- Web mock-ups are finalized.

**Comment by MericKeskin** [comment]
- Upgraded web mock-ups slightly, if already added to report it is a choice to re-add.
- Mobile mock-ups are ready to be added to report.

**Comment by bakikucukcakiroglu** [comment]
- Images are given black radius since the white background interferes with background of the Github if light theme is used. 

- Mobile and Web Mockups are uploaded to Milestone 1 Report. 

<img width="921" alt="Screen Shot 2023-04-10 at 14 31 31" src="https://user-images.githubusercontent.com/61244299/230893998-03749983-8d88-456c-956a-6368b73c25e5.png">
<img width="656" alt="Screen Shot 2023-04-10 at 14 31 41" src="https://user-images.githubusercontent.com/61244299/230894019-dd421268-a7f3-4a9e-95f4-d0f1ae09ccd5.png">
